//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuSatisOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int orderID { get; set; }
        public int customerID { get; set; }
        public string status { get; set; }
        public int price { get; set; }
        public System.DateTime createdAt { get; set; }
    
        public virtual Customers Customers { get; set; }
    }
}
